services:
  web:
    restart: always
    image: craftcms/nginx:8.1
    ports:
      - 8080:8080
    volumes:
      - .:/app

  db:
    restart: always
    image: mariadb:10.8
    ports:
      - 3306:3306
    environment:
      MARIADB_USER: db
      MARIADB_PASSWORD: db
      MARIADB_DATABASE: db
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
