field: 85c940f6-bd12-409a-ba09-e89808e51588 # Content blocks
fieldLayouts:
  65ba7d53-513d-4668-9969-7b0e90beaef1:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 6fa14b32-f1fa-47a6-8f89-4cfa9f57d553 # Images
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: cc2870b6-f20e-4866-809c-f72a62bf7b64
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 731fccf2-b21e-40b6-9891-8fe08acad0b4 # Loop
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 33488228-84d1-4549-be5d-ce5e10801cfd
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: f2368203-b60a-48b0-9a3f-381e7b52be93 # Image ratio
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 653089cb-e679-4dd3-ad7a-adf0f203d5a2
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: f89ccc3e-e3ce-4f6f-8e5b-71e3061ccd6b # Layout
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c658c8d4-3211-4698-bf0b-b353003d4aa1
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 6e6548c2-a1c2-4da4-9a41-4340c937f23e
        userCondition: null
fields:
  6fa14b32-f1fa-47a6-8f89-4cfa9f57d553: # Images
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: images
    instructions: null
    name: Images
    searchable: false
    settings:
      allowSelfRelations: false
      allowSubfolders: false
      allowUploads: true
      allowedKinds:
        - image
      branchLimit: null
      defaultUploadLocationSource: 'volume:839ae2cf-f27c-437d-8638-e143ed7dc237' # Images
      defaultUploadLocationSubpath: null
      localizeRelations: false
      maintainHierarchy: false
      maxRelations: null
      minRelations: null
      previewMode: full
      restrictFiles: true
      restrictLocation: false
      restrictedDefaultUploadSubpath: null
      restrictedLocationSource: 'volume:839ae2cf-f27c-437d-8638-e143ed7dc237' # Images
      restrictedLocationSubpath: null
      selectionCondition:
        __assoc__:
          -
            - elementType
            - craft\elements\Asset
          -
            - fieldContext
            - global
          -
            - class
            - craft\elements\conditions\assets\AssetCondition
      selectionLabel: null
      showSiteMenu: true
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      sources:
        - 'volume:839ae2cf-f27c-437d-8638-e143ed7dc237' # Images
      targetSiteId: null
      validateRelatedElements: false
      viewMode: large
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
  731fccf2-b21e-40b6-9891-8fe08acad0b4: # Loop
    columnSuffix: gyvjctcs
    contentColumnType: boolean
    fieldGroup: null
    handle: loop
    instructions: 'WARNING: You are recommended to keep this OFF because it can cause a bug in the slider! You''ll see for yourself.'
    name: Loop
    searchable: false
    settings:
      default: false
      offLabel: null
      onLabel: null
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Lightswitch
  f89ccc3e-e3ce-4f6f-8e5b-71e3061ccd6b: # Layout
    columnSuffix: xhfmeqcb
    contentColumnType: string(5)
    fieldGroup: null
    handle: layout
    instructions: null
    name: Layout
    searchable: false
    settings:
      columnType: null
      options:
        -
          __assoc__:
            -
              - label
              - Boxed
            -
              - value
              - boxed
            -
              - default
              - '1'
        -
          __assoc__:
            -
              - label
              - Wide
            -
              - value
              - wide
            -
              - default
              - ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Dropdown
  f2368203-b60a-48b0-9a3f-381e7b52be93: # Image ratio
    columnSuffix: blwxukkr
    contentColumnType: string(11)
    fieldGroup: null
    handle: imageRatio
    instructions: null
    name: 'Image ratio'
    searchable: false
    settings:
      columnType: null
      options:
        -
          __assoc__:
            -
              - label
              - Default
            -
              - value
              - default
            -
              - default
              - '1'
        -
          __assoc__:
            -
              - label
              - 1/1
            -
              - value
              - aspect-1/1
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - 4/3
            -
              - value
              - aspect-4/3
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - 5/2
            -
              - value
              - aspect-5/2
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - 16/9
            -
              - value
              - aspect-16/9
            -
              - default
              - ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Dropdown
handle: image
name: Image
sortOrder: 2
