field: 7d1cde09-7f5f-495f-a4c0-8bd783d3c328 # Infobox
fieldLayouts:
  e1452e12-d115-41b8-bf5e-8b9dba755105:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 25e87bb8-0f06-4188-8853-66b67a9ed4cd # Title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 239f73eb-4b5b-4bb8-9d83-6152f9a3580d
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 11a23a8e-4161-498e-a186-17f3a02eee93 # Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: bec3439d-fb3f-4eb7-b5df-1fe25e065121
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 3069c1ee-90d5-4fb8-ba90-bf50c4231395 # Tables
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ad133cec-a15e-45e9-bafd-494c7d3e2812
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 47f831e3-5f78-4ae8-b2b7-2f167cf7c528
        userCondition: null
fields:
  11a23a8e-4161-498e-a186-17f3a02eee93: # Image
    columnSuffix: iprhmtij
    contentColumnType: text
    fieldGroup: null
    handle: image
    instructions: null
    name: Image
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  25e87bb8-0f06-4188-8853-66b67a9ed4cd: # Title
    columnSuffix: nenwgnmz
    contentColumnType: text
    fieldGroup: null
    handle: headerText
    instructions: null
    name: Title
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  3069c1ee-90d5-4fb8-ba90-bf50c4231395: # Tables
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: tables
    instructions: null
    name: Tables
    searchable: false
    settings:
      blockTypeFields: 0
      changedFieldIndicator: 559975799
      columns:
        __assoc__:
          -
            - a6c52aef-1e3b-4ac2-819d-af905492c082 # Header
            -
              __assoc__:
                -
                  - width
                  - ''
          -
            - 386c9f6a-51d6-4498-ba11-99477985908d # Table
            -
              __assoc__:
                -
                  - width
                  - ''
      contentTable: '{{%stc_3_tables}}'
      fieldLayout: matrix
      maxRows: null
      minRows: null
      propagationKeyFormat: null
      propagationMethod: all
      selectionLabel: null
      staticField: null
    translationKeyFormat: null
    translationMethod: none
    type: verbb\supertable\fields\SuperTableField
handle: infobox
name: Infobox
sortOrder: 1
