field: 85c940f6-bd12-409a-ba09-e89808e51588 # Content blocks
fieldLayouts:
  92183113-c9c0-4352-822a-18e740ddf464:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 6241c26f-d8e2-430b-8d82-e337443c3ec0 # Text
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: eae47944-521d-4918-b56d-6e05c4d47411
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: dfa45180-35fd-4dca-9038-86c090f38795
        userCondition: null
fields:
  6241c26f-d8e2-430b-8d82-e337443c3ec0: # Text
    columnSuffix: kllndwvz
    contentColumnType: text
    fieldGroup: null
    handle: body
    instructions: null
    name: Text
    searchable: false
    settings:
      availableTransforms: ''
      availableVolumes: '*'
      ckeConfig: fc102a87-0ea8-4b4e-969a-5c267f78fe3e # Advanced
      columnType: text
      defaultTransform: null
      enableSourceEditingForNonAdmins: false
      purifierConfig: null
      purifyHtml: true
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      showWordCount: true
      wordLimit: null
    translationKeyFormat: null
    translationMethod: none
    type: craft\ckeditor\Field
handle: text
name: Text
sortOrder: 1
