color: null
fieldLayouts:
  add8c540-e329-4996-a142-833f38b02240:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 34d2d0de-2d8b-4612-b797-a58f38a432d5
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 945a92b7-6991-438d-a6e5-83178d2900c1 # Author
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 1c2581b8-3ce1-4039-a0b7-a2b312025123
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 38f2889b-aa09-4eb1-9130-20289cb83756 # Date
            handle: null
            includeInCards: false
            instructions: 'The date this blog post was authored. If unprovided, the entry''s creation date will be used.'
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c87c78f8-4b21-4c37-af62-5cd1c29d5530
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 1773497c-af9b-4c16-abbf-6bff44a59d6f # Blog tags
            handle: null
            includeInCards: false
            instructions: null
            label: Tags
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 03a735fa-5065-46e9-b48f-791a92a536ad
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            type: craft\fieldlayoutelements\HorizontalRule
            uid: e3c1effe-6670-47cb-94dc-3f4a0c8123b0
            userCondition: null
          -
            elementCondition: null
            fieldUid: 3db08b57-f3d4-4d95-882a-df1dce6941e0 # Header image
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 9c7f0f24-9038-40f2-aa7d-e4d81f3cdc74
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            type: craft\fieldlayoutelements\HorizontalRule
            uid: 24d49e7a-064f-4c7c-9baf-8e32f2b9664b
            userCondition: null
          -
            elementCondition: null
            fieldUid: 86fefa4d-a9eb-4b7f-a61d-004fe86777ec # Links
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 9e33cae6-287d-4edb-a3d3-208a786bf4ca
            userCondition: null
            warning: null
            width: 100
        name: Meta
        uid: cfe275d9-434c-4d12-9af9-237c98c85ea3
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: f4bb6200-34bc-40a3-a178-12160c9f2ddf # Overview image
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 97a20750-21bd-4bda-bb74-e04949756290
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 85c940f6-bd12-409a-ba09-e89808e51588 # Content blocks
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 240bd130-eade-4d66-9858-d9e66bfe8087
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 7b4fa632-9a7a-4d1d-9eaa-a21cda7030de
        userCondition: null
handle: blogPosts
hasTitleField: true
icon: null
name: 'Blog posts'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
