color: null
fieldLayouts:
  2e1508e4-bbac-46dc-831a-2fa31b4e9598:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: b181db25-f403-4546-b2b0-2fa033618320
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 3db08b57-f3d4-4d95-882a-df1dce6941e0 # Header image
            handle: profilePicture
            includeInCards: false
            instructions: null
            label: 'Profile picture'
            providesThumbs: false
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: dfa96200-1222-466c-943f-e7e51f05f918
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 4a2babac-f97c-4e71-8e7e-d6dfec11cc7e # Description
            handle: introduction
            includeInCards: false
            instructions: 'Introduce yourself!'
            label: Introduction
            providesThumbs: false
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 4c2da9fc-914b-4c96-ae0a-513cc012991a
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: b653c91e-0112-4c5b-aff3-7db16183aa7f # Socials
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a69155a6-7500-4430-bcde-213e95520d6b
            userCondition: null
            warning: null
            width: 100
        name: Header
        uid: 1e732958-f7e5-4d2f-8542-26648e133416
        userCondition: null
handle: header
hasTitleField: false
icon: ''
name: Header
showSlugField: true
showStatusField: false
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: Header
titleTranslationKeyFormat: null
titleTranslationMethod: site
