color: violet
fieldLayouts:
  dcfff9e5-3ee2-4c0e-a4f3-65c198741350:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: f6f0f7d3-fde8-4760-8128-ec2a0afd835f
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 3db08b57-f3d4-4d95-882a-df1dce6941e0 # Header image
            handle: profilePicture
            includeInCards: false
            instructions: null
            label: 'Profile picture'
            providesThumbs: false
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 9be47a74-45b6-4b22-8d37-60c63d98e5db
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 4a2babac-f97c-4e71-8e7e-d6dfec11cc7e # Description
            handle: introduction
            includeInCards: false
            instructions: 'Introduce yourself!'
            label: Introduction
            providesThumbs: false
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: cff0ca56-0111-48bc-9792-c8860c257136
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: b653c91e-0112-4c5b-aff3-7db16183aa7f # Socials
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d00690d3-7754-4991-99d6-a819f962bfdf
            userCondition: null
            warning: null
            width: 100
        name: Header
        uid: 5f16205f-6e19-4548-a871-66d767bd23e8
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 85c940f6-bd12-409a-ba09-e89808e51588 # Content blocks
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 6a3012bb-b457-47a7-86b7-715162df1391
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 00473311-2224-47d4-a1d3-65486288c3fb
        userCondition: null
handle: homepage
hasTitleField: true
icon: house
name: Homepage
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
