color: violet
fieldLayouts:
  dcfff9e5-3ee2-4c0e-a4f3-65c198741350:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: f6f0f7d3-fde8-4760-8128-ec2a0afd835f
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 85c940f6-bd12-409a-ba09-e89808e51588 # Content blocks
            handle: null
            includeInCards: false
            instructions: 'Additional content blocks to show below the project listing. You shouldn''t have to edit this.'
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 6a3012bb-b457-47a7-86b7-715162df1391
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 00473311-2224-47d4-a1d3-65486288c3fb
        userCondition: null
handle: homepage
hasTitleField: false
icon: house
name: Homepage
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
