color: null
fieldLayouts:
  32d4f259-9a8d-4f70-87bb-0e10bd903394:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: e36d3e76-6da4-422f-a7a5-1aa3a333970b
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 25e87bb8-0f06-4188-8853-66b67a9ed4cd # Header text
            handle: null
            includeInCards: true
            instructions: null
            label: null
            providesThumbs: false
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 781f8eb3-0b59-40bf-bd80-b9db70e97457
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 386c9f6a-51d6-4498-ba11-99477985908d # Infobox - Infobox - Tables - Table
            handle: null
            includeInCards: false
            instructions: null
            label: Table
            providesThumbs: false
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e9eefdcc-5b55-4d7e-bad9-7fb00f89f1af
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 90431127-7272-475f-a1a9-a128c32e7555
        userCondition: null
handle: tablesBlock
hasTitleField: false
icon: null
name: 'Infobox - Infobox - Tables Block'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
