fieldLayouts:
  f8c25569-35a7-41ab-9cdb-b6365face254:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: e49cef65-ced7-46f6-b22a-89535be1d6a6
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 85c940f6-bd12-409a-ba09-e89808e51588 # Content blocks
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 8c6b6afa-a029-473c-bab9-14eb7e3b4fda
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 0dab5f18-44da-4ff2-a3f8-2208c6781bec
        userCondition: null
handle: templateBlocks_default
hasTitleField: true
name: 'Template blocks - Default'
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
