color: null
fieldLayouts:
  d5f32124-a8ab-4d12-b9fe-840cbaafbeed:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 9962751c-10cc-48cb-90ae-a9ea7c495f78
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 859b7ba4-9e42-468c-894f-e21942c422b4 # Text
            handle: null
            includeInCards: true
            instructions: null
            label: Text
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c58d7956-d203-4c4a-a3a5-6aeecf6dc36b
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 6fa14b32-f1fa-47a6-8f89-4cfa9f57d553 # Images
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: true
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d5bad9de-479d-408a-a479-e2ecca74b43f
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 6214ac56-b752-499c-95a2-984f94640f8c # Image ratio
            handle: null
            includeInCards: false
            instructions: null
            label: 'Image ratio'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c31827f2-46f9-4e0d-9cd6-58089b04ee41
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 411ebf8a-0478-40b9-a5fc-8b83e01c14e7 # Content blocks - Text with media - Image position
            handle: null
            includeInCards: false
            instructions: null
            label: 'Image position'
            providesThumbs: false
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b75bf0e8-4eb8-40d6-b660-4ca020374234
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 6cf7cf3c-bc05-4ed6-9ff3-3062822901f4 # Layout
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 37305171-1be5-45c1-97d1-061146d93035
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 42c31269-661e-4825-9c6b-d4376ffdb570
        userCondition: null
handle: textWithMedia
hasTitleField: false
icon: null
name: 'Text with media'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
