color: null
fieldLayouts:
  d5f32124-a8ab-4d12-b9fe-840cbaafbeed:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 859b7ba4-9e42-468c-894f-e21942c422b4
            handle: null
            includeInCards: true
            instructions: null
            label: Text
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c58d7956-d203-4c4a-a3a5-6aeecf6dc36b
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 2778964a-6289-4f09-9401-73f7c2ce1a04
            handle: null
            includeInCards: false
            instructions: null
            label: Images
            providesThumbs: true
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 3261ecf7-a3e3-445e-9bec-9a43c0258905
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 6214ac56-b752-499c-95a2-984f94640f8c
            handle: null
            includeInCards: false
            instructions: null
            label: 'Image ratio'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c31827f2-46f9-4e0d-9cd6-58089b04ee41
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 411ebf8a-0478-40b9-a5fc-8b83e01c14e7
            handle: null
            includeInCards: false
            instructions: null
            label: 'Image position'
            providesThumbs: false
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b75bf0e8-4eb8-40d6-b660-4ca020374234
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: fa1750fd-9d5e-45a2-a7b7-aa88f3d5b513
            handle: layout
            includeInCards: false
            instructions: null
            label: Layout
            providesThumbs: false
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c4e7809a-40d7-4920-91ee-37b1ca64b9a1
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 42c31269-661e-4825-9c6b-d4376ffdb570
        userCondition: null
handle: textWithMedia
hasTitleField: false
icon: null
name: 'Text with media'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
