color: null
fieldLayouts:
  92183113-c9c0-4352-822a-18e740ddf464:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 23ab6ada-19d3-4430-a3b5-0810987ecb87
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 859b7ba4-9e42-468c-894f-e21942c422b4 # Text
            handle: null
            includeInCards: true
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 60bf2737-7e68-4f61-8406-809f65563135
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: dfa45180-35fd-4dca-9038-86c090f38795
        userCondition: null
handle: text
hasTitleField: false
icon: null
name: Text
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
