defaultPlacement: end
fieldLayouts:
  42c3846d-ab3f-4c45-8883-12ee957626a7:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\TitleField
            uid: c02a60e1-e712-4ba3-b2ec-a3f366e4e1ad
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 4a2babac-f97c-4e71-8e7e-d6dfec11cc7e # Description
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: fb21132e-0627-4b0d-b366-1019ac676d58
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: e2bc1cd0-7aeb-4fe9-b8c3-8f50c83153d4
        userCondition: null
handle: projects
name: Projects
siteSettings:
  56778e37-c05d-4b72-9057-434d06389bd1: # Ossyweb
    hasUrls: false
    template: null
    uriFormat: null
structure:
  maxLevels: null
  uid: f327c3b8-4417-484e-963c-cb37461c5ceb
