columnSuffix: czrtlqju
handle: authoredBy
instructions: 'The author of the post.'
name: Author
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: false
  initialRows: 4
  multiline: false
  placeholder: Ossian
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
