columnSuffix: null
handle: blogTags
instructions: null
name: 'Blog tags'
searchable: true
settings:
  allowSelfRelations: false
  branchLimit: null
  localizeRelations: false
  maintainHierarchy: false
  maxRelations: null
  minRelations: null
  selectionLabel: 'Add a tag'
  showCardsInGrid: false
  showSiteMenu: true
  sources:
    - 'section:ab712c4b-2876-4b6a-9d0d-de9a79fd4378' # Blog tags
  targetSiteId: null
  validateRelatedElements: false
  viewMode: list
translationKeyFormat: null
translationMethod: site
type: craft\fields\Entries
