columnSuffix: null
contentColumnType: string
handle: contentBlocks
instructions: 'Post contents.'
name: 'Content blocks'
searchable: false
settings:
  entryTypes:
    - 3e3f1077-a7fc-4cdc-a11b-963c9139b430
    - 86c57f7d-a69e-4d4b-976a-8bd3f43a1a91
    - 605e98e8-f8bc-4034-8a2e-97672f873454
    - 39455dac-8f36-4b6b-a4af-d933d339d918
    - ccc8c64c-9c60-49be-9c7b-2a1911394d95
  maxEntries: null
  minEntries: 0
  propagationKeyFormat: null
  propagationMethod: all
  viewMode: blocks
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
