columnSuffix: null
contentColumnType: string
fieldGroup: 92a92774-b6e2-451e-966b-1c26b0bcb790 # Common
handle: contentBlocks
instructions: 'Post contents.'
name: 'Content blocks'
searchable: false
settings:
  contentTable: '{{%matrixcontent_contentblocks}}'
  maxBlocks: null
  minBlocks: 0
  propagationKeyFormat: null
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
