columnSuffix: hfdhjcvy
contentColumnType:
  - 'date:datetime'
  - 'tz:string'
handle: date
instructions: 'The date this blog post was authored. If unprovided, the entry''s creation date will be used.'
name: Date
searchable: false
settings:
  max: null
  min: null
  minuteIncrement: 30
  showDate: true
  showTime: true
  showTimeZone: true
translationKeyFormat: null
translationMethod: none
type: craft\fields\Date
