columnSuffix: warvskqs
handle: imageRatio
instructions: null
name: 'Image ratio'
searchable: false
settings:
  options:
    -
      __assoc__:
        -
          - label
          - Default
        -
          - value
          - default
        -
          - default
          - '1'
    -
      __assoc__:
        -
          - label
          - 1/1
        -
          - value
          - aspect-1/1
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - 4/3
        -
          - value
          - aspect-4/3
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - 5/2
        -
          - value
          - aspect-5/2
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - 16/9
        -
          - value
          - aspect-16/9
        -
          - default
          - ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\Dropdown
