columnSuffix: null
contentColumnType: string
handle: infobox
instructions: null
name: Infobox
searchable: false
settings:
  entryTypes:
    - b551bf6a-c784-4830-98d0-cf532519e326
  maxEntries: 1
  minEntries: null
  propagationKeyFormat: null
  propagationMethod: all
  viewMode: blocks
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
