columnSuffix: mtnxfsce
handle: layout2
instructions: null
name: 'Content blocks - Text with media - Layout'
searchable: false
settings:
  options:
    -
      __assoc__:
        -
          - label
          - Boxed
        -
          - value
          - boxed
        -
          - default
          - '1'
    -
      __assoc__:
        -
          - label
          - Wide
        -
          - value
          - wide
        -
          - default
          - ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\Dropdown
