columnSuffix: enivplxu
handle: layout
instructions: null
name: 'Content blocks - Video - Layout'
searchable: false
settings:
  options:
    -
      __assoc__:
        -
          - label
          - Boxed
        -
          - value
          - boxed
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - Wide
        -
          - value
          - wide
        -
          - default
          - ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\Dropdown
