columnSuffix: hxfqaawg
handle: position
instructions: null
name: 'Content blocks - Text with media - Image position'
searchable: false
settings:
  default: left
  options:
    __assoc__:
      -
        - left
        - '1'
      -
        - center
        - ''
      -
        - right
        - '1'
      -
        - full
        - ''
      -
        - drop-left
        - ''
      -
        - drop-right
        - ''
translationKeyFormat: null
translationMethod: none
type: rias\positionfieldtype\fields\Position
