columnSuffix: null
handle: project
instructions: null
name: Project
searchable: false
settings:
  allowSelfRelations: false
  branchLimit: null
  localizeRelations: false
  maintainHierarchy: false
  maxRelations: 1
  minRelations: 1
  selectionLabel: 'Select a project'
  showCardsInGrid: false
  showSiteMenu: true
  sources:
    - 'section:8eeba85a-6be4-4180-a67f-b6aae930591c' # Projects
  targetSiteId: null
  validateRelatedElements: false
  viewMode: list
translationKeyFormat: null
translationMethod: site
type: craft\fields\Entries
