columnSuffix: null
handle: socials
instructions: null
name: Socials
searchable: false
settings:
  addRowLabel: 'Add a row'
  columns:
    __assoc__:
      -
        - col1
        -
          __assoc__:
            -
              - heading
              - Platform
            -
              - handle
              - platform
            -
              - width
              - ''
            -
              - type
              - select
            -
              - options
              -
                -
                  __assoc__:
                    -
                      - label
                      - Facebook
                    -
                      - value
                      - facebook
                    -
                      - default
                      - false
                -
                  __assoc__:
                    -
                      - label
                      - Instagram
                    -
                      - value
                      - instagram
                    -
                      - default
                      - false
                -
                  __assoc__:
                    -
                      - label
                      - Twitter
                    -
                      - value
                      - twitter
                    -
                      - default
                      - false
                -
                  __assoc__:
                    -
                      - label
                      - Mastodon
                    -
                      - value
                      - mastodon
                    -
                      - default
                      - false
                -
                  __assoc__:
                    -
                      - label
                      - Spotify
                    -
                      - value
                      - spotify
                    -
                      - default
                      - false
                -
                  __assoc__:
                    -
                      - label
                      - Bandcamp
                    -
                      - value
                      - bandcamp
                    -
                      - default
                      - false
      -
        - col2
        -
          __assoc__:
            -
              - heading
              - URL
            -
              - handle
              - url
            -
              - width
              - ''
            -
              - type
              - singleline
  defaults: null
  maxRows: null
  minRows: null
  staticRows: false
translationKeyFormat: null
translationMethod: none
type: craft\fields\Table
