columnSuffix: wikqknta
contentColumnType: text
fieldGroup: 153a5705-0659-4f36-85d4-99f781890f90 # Blog
handle: tags
instructions: 'Tags for this post. These are filterable on the frontend, so you''re responsible for making sure there are no typos in tags if you want to group posts together.'
name: Tags
searchable: true
settings:
  addRowLabel: 'Add a row'
  columnType: text
  columns:
    __assoc__:
      -
        - col1
        -
          __assoc__:
            -
              - heading
              - 'Tag name'
            -
              - handle
              - tagName
            -
              - width
              - ''
            -
              - type
              - singleline
  defaults: null
  maxRows: null
  minRows: null
  staticRows: false
translationKeyFormat: null
translationMethod: none
type: craft\fields\Table
