columnSuffix: lhprtlfv
handle: videoFile
instructions: 'Overrides the video link.'
name: 'Content blocks - Video - Video file'
searchable: false
settings:
  allowSelfRelations: false
  allowSubfolders: false
  allowUploads: true
  allowedKinds:
    - video
  branchLimit: null
  defaultUploadLocationSource: 'volume:a008d84a-363c-4834-8a89-452dc77f7d1c' # Files
  defaultUploadLocationSubpath: Video
  localizeRelations: false
  maintainHierarchy: false
  maxRelations: 1
  minRelations: null
  previewMode: full
  restrictFiles: true
  restrictLocation: false
  restrictedDefaultUploadSubpath: null
  restrictedLocationSource: 'volume:839ae2cf-f27c-437d-8638-e143ed7dc237' # Images
  restrictedLocationSubpath: null
  selectionLabel: 'Add a video'
  showCardsInGrid: false
  showSiteMenu: true
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  sources:
    - 'volume:a008d84a-363c-4834-8a89-452dc77f7d1c' # Files
  targetSiteId: null
  validateRelatedElements: false
  viewMode: list
translationKeyFormat: null
translationMethod: site
type: craft\fields\Assets
