dateModified: 1719249407
email:
  fromEmail: alyxia@riseup.net
  fromName: Ossyweb
  transportType: craft\mail\transportadapters\Sendmail
fs:
  files:
    hasUrls: true
    name: Files
    settings:
      path: '@webroot/assets/files'
    type: craft\fs\Local
    url: '@web/assets/files'
  images:
    hasUrls: true
    name: Images
    settings:
      path: '@webroot/assets/images'
    type: craft\fs\Local
    url: '@web/assets/images'
meta:
  __names__:
    3ba6e933-d79e-47fc-9f59-c8a854e88a04: 'Blog tag' # Blog tag
    3db08b57-f3d4-4d95-882a-df1dce6941e0: 'Header image' # Header image
    3e3f1077-a7fc-4cdc-a11b-963c9139b430: 'Default block' # Default block
    4a2babac-f97c-4e71-8e7e-d6dfec11cc7e: Description # Description
    4e04925d-53af-439f-b5b0-80a29385e89c: Project # Project
    5deffeba-4b22-4b86-bc22-7b847b5d2271: Caption # Caption
    6a6f6930-cbb7-4e51-8eea-1b7db3a75d25: Header # Header
    6c1c2f5f-4865-446b-adbe-963bc320004f: 'Blog overview' # Blog overview
    6c815cf0-1120-459b-a4af-6683dc27784d: 'Content blocks - Video - Video type' # Content blocks - Video - Video type
    6cf7cf3c-bc05-4ed6-9ff3-3062822901f4: Layout # Layout
    6fa14b32-f1fa-47a6-8f89-4cfa9f57d553: Images # Images
    7d1cde09-7f5f-495f-a4c0-8bd783d3c328: Infobox # Infobox
    8ba5f4b6-0208-42fe-8e87-e4bfd2098698: 'Infobox - Infobox - Tables Block' # Infobox - Infobox - Tables Block
    8eeba85a-6be4-4180-a67f-b6aae930591c: Projects # Projects
    11a23a8e-4161-498e-a186-17f3a02eee93: 'Infobox - Infobox - Image' # Infobox - Infobox - Image
    25e87bb8-0f06-4188-8853-66b67a9ed4cd: 'Header text' # Header text
    38f2889b-aa09-4eb1-9130-20289cb83756: Date # Date
    48dc4bd9-11d8-4743-80b5-96d05be09cec: 'Content blocks - Video - Video link' # Content blocks - Video - Video link
    62e1584f-a2b4-4564-8340-b3a9bf31846b: Block # Block
    70b859f6-1e85-44a3-b3ae-e169ebecadb3: Homepage # Homepage
    75aebda1-d2ea-4d01-8588-dcd06e935fd1: 'Wiki page' # Wiki page
    83db3eee-a8af-4f85-a62d-8cf58e811498: 'Blog posts' # Blog posts
    85c940f6-bd12-409a-ba09-e89808e51588: 'Content blocks' # Content blocks
    86c57f7d-a69e-4d4b-976a-8bd3f43a1a91: Video # Video
    86fefa4d-a9eb-4b7f-a61d-004fe86777ec: Links # Links
    386c9f6a-51d6-4498-ba11-99477985908d: 'Infobox - Infobox - Tables - Table' # Infobox - Infobox - Tables - Table
    411ebf8a-0478-40b9-a5fc-8b83e01c14e7: 'Content blocks - Text with media - Image position' # Content blocks - Text with media - Image position
    605e98e8-f8bc-4034-8a2e-97672f873454: 'Text with media' # Text with media
    731fccf2-b21e-40b6-9891-8fe08acad0b4: 'Content blocks - Image - Loop' # Content blocks - Image - Loop
    839ae2cf-f27c-437d-8638-e143ed7dc237: Images # Images
    859b7ba4-9e42-468c-894f-e21942c422b4: Text # Text
    889dccfc-8cd0-443e-8311-7891f4507e8e: Simple # Simple
    945a92b7-6991-438d-a6e5-83178d2900c1: Author # Author
    2984f79f-c827-46a5-a2cd-47eb998cde86: 'Content pages - Default' # Content pages - Default
    3069c1ee-90d5-4fb8-ba90-bf50c4231395: 'Infobox - Infobox - Tables' # Infobox - Infobox - Tables
    3786f902-0889-45da-8b67-5c42bf51221f: 'Template blocks - Default' # Template blocks - Default
    6214ac56-b752-499c-95a2-984f94640f8c: 'Image ratio' # Image ratio
    7563f668-17c4-4e35-8498-c58be8ded69c: 'Public Schema' # Public Schema
    39455dac-8f36-4b6b-a4af-d933d339d918: Text # Text
    56778e37-c05d-4b72-9057-434d06389bd1: Ossyweb # Ossyweb
    532263ad-20bf-4295-9d54-146d12a40216: 'Wiki pages' # Wiki pages
    757075c4-b94f-4be4-b55a-de554eb8b122: 'Blog post' # Blog post
    1773497c-af9b-4c16-abbf-6bff44a59d6f: 'Blog tags' # Blog tags
    a008d84a-363c-4834-8a89-452dc77f7d1c: Files # Files
    ab712c4b-2876-4b6a-9d0d-de9a79fd4378: 'Blog tags' # Blog tags
    b551bf6a-c784-4830-98d0-cf532519e326: Infobox # Infobox
    b553fa53-583f-4453-a2a5-5d729fc1a4dc: Project # Project
    b653c91e-0112-4c5b-aff3-7db16183aa7f: Socials # Socials
    be9998d7-eb61-4f23-8102-da26d48440b7: 'Content blocks - Video - Video file' # Content blocks - Video - Video file
    ccc8c64c-9c60-49be-9c7b-2a1911394d95: Image # Image
    d98cc2ec-cb65-4243-9992-5a52efd1f2a2: Header # Header
    dbb362d2-cf9d-4721-8b28-55f4f8e9cdae: 'Content blocks - Video - Placeholder image' # Content blocks - Video - Placeholder image
    ea4268bc-078c-437b-98b9-849a236599b4: Homepage # Homepage
    ef8f836c-1e3e-4c08-b6ac-678de5511aaa: Ossyweb # Ossyweb
    f4bb6200-34bc-40a3-a178-12160c9f2ddf: 'Overview image' # Overview image
    f80baea6-6de5-4cad-a2a5-3d0df3dca2d2: 'Template blocks' # Template blocks
    f83161a7-6fcf-4ceb-bebe-56bb0b870f7d: 'Content pages' # Content pages
    fc102a87-0ea8-4b4e-969a-5c267f78fe3e: Advanced # Advanced
plugins:
  ckeditor:
    edition: standard
    enabled: true
    schemaVersion: 3.0.0.0
  imager-x:
    edition: pro
    enabled: true
    licenseKey: HZG0ZPJLRI7D4X7DZ50ZFAA8
    schemaVersion: 4.0.0
  inlinesvg:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  minify:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  position-fieldtype:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  tablemaker:
    edition: standard
    enabled: true
    schemaVersion: 3.0.0
  vite:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
system:
  edition: solo
  live: true
  name: Ossyweb
  retryDuration: null
  schemaVersion: 5.0.0.20
  timeZone: Europe/Amsterdam
