defaultPlacement: end
enableVersioning: true
entryTypes:
  - 6c1c2f5f-4865-446b-adbe-963bc320004f # Blog overview
handle: blogOverview
maxAuthors: 1
name: 'Blog overview'
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
propagationMethod: all
siteSettings:
  56778e37-c05d-4b72-9057-434d06389bd1: # Ossyweb
    enabledByDefault: true
    hasUrls: true
    template: _sections/blog/index
    uriFormat: blog
type: single
