defaultPlacement: end
enableVersioning: true
handle: blogOverview
name: 'Blog overview'
propagationMethod: all
siteSettings:
  56778e37-c05d-4b72-9057-434d06389bd1: # Ossyweb
    enabledByDefault: true
    hasUrls: true
    template: _sections/blog/index
    uriFormat: blog
type: single
