defaultPlacement: end
enableVersioning: true
entryTypes:
  - 3ba6e933-d79e-47fc-9f59-c8a854e88a04 # Blog tag
handle: blogTags
maxAuthors: 1
name: 'Blog tags'
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  56778e37-c05d-4b72-9057-434d06389bd1: # Ossyweb
    enabledByDefault: true
    hasUrls: false
    template: null
    uriFormat: null
type: channel
