defaultPlacement: end
enableVersioning: true
entryTypes:
  - 2984f79f-c827-46a5-a2cd-47eb998cde86 # Content pages - Default
handle: contentPages
maxAuthors: 1
name: 'Content pages'
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
propagationMethod: all
siteSettings:
  56778e37-c05d-4b72-9057-434d06389bd1: # Ossyweb
    enabledByDefault: true
    hasUrls: true
    template: _sections/content/entry
    uriFormat: '{slug}'
type: channel
