defaultPlacement: end
enableVersioning: true
entryTypes:
  - 70b859f6-1e85-44a3-b3ae-e169ebecadb3 # Homepage
handle: homepage
maxAuthors: 1
name: Homepage
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
propagationMethod: all
siteSettings:
  56778e37-c05d-4b72-9057-434d06389bd1: # Ossyweb
    enabledByDefault: true
    hasUrls: true
    template: index
    uriFormat: __home__
type: single
