defaultPlacement: end
enableVersioning: true
handle: homepage
name: Homepage
propagationMethod: all
siteSettings:
  56778e37-c05d-4b72-9057-434d06389bd1: # Ossyweb
    enabledByDefault: true
    hasUrls: true
    template: index
    uriFormat: __home__
type: single
