defaultPlacement: end
enableVersioning: true
handle: templateBlocks
name: 'Template blocks'
propagationMethod: all
siteSettings:
  56778e37-c05d-4b72-9057-434d06389bd1: # Ossyweb
    enabledByDefault: true
    hasUrls: true
    template: _sections/standardBlocks/_entry.twig
    uriFormat: '{slug}'
type: channel
