defaultPlacement: end
enableVersioning: true
entryTypes:
  - 3786f902-0889-45da-8b67-5c42bf51221f # Template blocks - Default
handle: templateBlocks
maxAuthors: 1
name: 'Template blocks'
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
propagationMethod: all
siteSettings:
  56778e37-c05d-4b72-9057-434d06389bd1: # Ossyweb
    enabledByDefault: true
    hasUrls: true
    template: _sections/standardBlocks/_entry.twig
    uriFormat: '{slug}'
type: channel
